config/routes.rb
Rails.application.routes.draw do
  resources :groups
  root to: "homes#show"

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy] do
    collection do
      post :ready
      post :validate
    end
  end

  resource :homes, only: [:show], :path => "/" do
    collection do
      get :contact
      get :books
      get :about
      get :backdoor
      post :email
      get :privacy
      get :whitelist
      get :signup
      get :subscribed
      get :thank_you
    end
  end

  resources :news_items
  resources :subscriptions, only: [:create]
end

app/models/news_item.rb
class NewsItem < ApplicationRecord
  validates :posted_date, presence: true
  validates :title, presence: true, length: { in: 1..100 }
  validates :friendly_link, length: { in: 0..25 }, allow_blank: true

  has_one_attached :picture
  belongs_to :group, optional: true

  scope :books, -> { where(is_book: true) }
  scope :news, -> { where(is_news: true) }

  def display_types
    return "None" unless is_book || is_news

    retval = []
    retval << "Book" if is_book
    retval << "News" if is_news

    retval.join(', ')
  end
end

app/controllers/news_items_controller.rb
class NewsItemsController < ApplicationController
  before_action :ensure_admin, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_news_item, only: [:show, :edit, :update, :destroy]

  def index
    @news_items = NewsItem.all
  end

  def show
    return redirect_to news_items_path if @news_item.nil?

    @subscription = Subscription.new
  end

  def new
    @news_item = NewsItem.new
  end

  def edit
  end

  def create
    @news_item = NewsItem.new(news_item_params)

    respond_to do |format|
      if @news_item.save
        @news_item.save
        format.html { redirect_to news_items_path, notice: 'news_item was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @news_item.update(news_item_params)
        @news_item.save
        format.html { redirect_to news_items_path, notice: 'news_item was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @news_item.destroy
    respond_to do |format|
      format.html { redirect_to news_items_url, notice: 'news_item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_news_item
      # @news_item = NewsItem.find(params[:id])

      # allow routing by name in addition to id
      if params[:id].match?(/\A\d+\Z/)
        # if passed a number, use :id
        @news_item = NewsItem.find(params[:id])
      else
        # if passed a name, use :username
        @news_item = NewsItem.find_by_friendly_link(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_item_params
      params.require(:news_item).permit(:posted_date, :title, :body, :picture, :is_book, :is_news, :piclink, :book_number, :group_id, :friendly_link)
    end
end

app/views/news_items/_form.html.erb
<%= form_with(model: news_item, local: true) do |f| %>
  <% if news_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(news_item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% news_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-4">
      <%= f.label :is_book, class: "font-weight-bold" do %>
        <%= f.check_box :is_book %>
        Book
      <% end %>
    </div>
    <div class="col-4">
      <%= f.label :is_news, class: "font-weight-bold" do %>
        <%= f.check_box :is_news %>
        News
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-8">
      <%= f.label :posted_date, "Date", class: "font-weight-bold" %>
      <div class="input-group input-group-lg">
        <%= f.text_field :posted_date, placeholder: " Type your Date here ",
          :data => {:provide => 'datepicker', 'date-format' => 'M dd, yyyy', 'date-autoclose' => 'true'},
          class: 'form-control input-lg date', :value => news_item&.posted_date&.strftime('%B %d, %Y') %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-8">
      <%= f.label :title, "Title", class: "font-weight-bold" %>
      <div class="input-group input-group-lg">
        <%= f.text_field :title, placeholder: " Type your Title here ", class: 'form-control input-lg' %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-8">
      <%= f.label :friendly_link, "Friendly Link", class: "font-weight-bold" %>
      <div class="input-group input-group-lg">
        <%= f.text_field :friendly_link, placeholder: " Type your Friendly Link here ", class: 'form-control input-lg', :maxlength => 25 %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-8">
      <%= f.label :group_id, "Series", class: "font-weight-bold" %>
      <div class="input-group input-group-lg">
        <%= f.select :group_id, Group.order(:ordering).collect {|p| [ p.name, p.id ] }, { include_blank: true } %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-8">
      <%= f.label :book_number, "Book Number", class: "font-weight-bold" %>
      <div class="input-group input-group-lg">
        <%= f.number_field :book_number, class: 'form-control input-lg' %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-8">
      <%= f.label :piclink, "Picture Link", class: "font-weight-bold" %>
      <div class="input-group input-group-lg">
        <%= f.text_field :piclink, placeholder: " The url link for the picutre ", class: 'form-control input-lg' %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-8">
      <% if news_item.picture.attached? %>
        <%= f.label :existing_picture, "Current Image File: " + news_item&.picture&.blob&.filename&.to_s, class: "font-weight-bold" %>
        <image src="<%= url_for(@news_item.picture) %>"></image>
        <div class="row">
          <div class="col-2"></div>
          <div class="col-8">
            <%= f.label :picture, "Change the Image", class: "font-weight-bold" %>
            <div class="input-group input-group-lg">
              <%= f.file_field :picture, class: 'form-control input-lg' %>
            </div>
          </div>
        </div>
      <% else %>
        <%= f.label :picture, "Image", class: "font-weight-bold" %>
        <div class="input-group input-group-lg">
          <%= f.file_field :picture, class: 'form-control input-lg' %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-8">
      <%= f.label :body, "Body", class: "font-weight-bold" %>
      <div class="input-group input-group-lg">
        <%= f.text_area :body, placeholder: " Type your Body here ", rows: "10", class: 'form-control input-lg', id: 'example' %>
      </div>
    </div>
  </div>


  <br><br>
  <div class="actions row">
    <div class="col-2">
      <%= f.submit "Save", class: 'btn btn-primary' %>
      <%= link_to 'Cancel', news_items_path, class: 'btn btn-warning' %>
    </div>
  </div>
<% end %>

<br><br>

app/views/news_items/edit.html.erb
<div class="container">
  <h1>Editing News Item</h1>
  <hr>
  <%= render 'form', news_item: @news_item %>
</div>

app/views/news_items/index.html.erb
<div class="container">
  <h1>News Items</h1>

  <table id="view-index" class="table table-striped table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Types</th>
        <th>Date</th>
        <th>Title</th>
        <th>Series</th>
        <th>Book Number</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @news_items.order("posted_date ASC").each do |news_item| %>
        <tr>
          <td><%= news_item.display_types %></td>
          <td><%= news_item.posted_date.strftime('%B %d, %Y') %></td>
          <td><%= news_item.title %></td>
          <td><%= news_item.group&.name %></td>
          <td><%= news_item.book_number %></td>
          <td>
            <%= link_to 'Change', edit_news_item_path(news_item), class: "badge badge-primary" %>
            <%= link_to 'Delete', news_item,
              data: {:confirm => 'Are you sure?'}, :method => :delete, class: "badge badge-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New News Item', new_news_item_path, class: 'btn btn-primary' %>
</div>

<br>
<div class="container">
<h1>Series</h1>

  <table id="view-index" class="table table-striped table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Name</th>
        <th>Ordering</th>
        <th></th>
      </tr>
    </thead>

  <tbody>
    <% Group.order(:ordering).each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.ordering %></td>
        <td><%= link_to 'Change', edit_group_path(group), class: "badge badge-primary" %>
            <%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' }, class: "badge badge-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Series', new_group_path, class: 'btn btn-primary' %>

</div>

app/views/news_items/new.html.erb
<div class="container">
  <h1>New News Item</h1>
  <hr>
  <%= render 'form', news_item: @news_item %>
</div>

app/views/news_items/show.html.erb
<div class="container">
  <hr>
  <div class="panel panel-default">
    <div class="panel-body">
      <div class="row">
        <div class="col-md-1"><b>Date</b></div>
        <div class="col-md-11"><%= @news_item.posted_date %></div>
      </div>

      <div class="row">
        <div class="col-md-1"><b>Title</b></div>
        <div class="col-md-11"><%= @news_item.title %></div>
      </div>

      <div class="row">
        <div class="col-md-1"><b>Image</b></div>
        <div class="col-md-11">
          <% if @news_item.picture.attached? %>
            <image src="<%= url_for(@news_item.picture) %>"></image>
          <% else %>
            None
          <% end %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-1"><b>Body</b></div>
        <div class="col-md-11"><%= @news_item.body %></div>
      </div>

      <!-- embed links table here -->
    </div>
  </div>
</div>