config/routes.rb
Rails.application.routes.draw do
  resources :groups
  root to: "homes#show"

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy] do
    collection do
      post :ready
      post :validate
    end
  end

  resource :homes, only: [:show], :path => "/" do
    collection do
      get :contact
      get :books
      get :about
      get :backdoor
      post :email
      get :privacy
      get :whitelist
      get :signup
      get :subscribed
      get :thank_you
    end
  end

  resources :news_items
  resources :subscriptions, only: [:create]
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
    @subscription = Subscription.new
    @posts = NewsItem.news.order("posted_date DESC").paginate(page: params[:page], per_page: APP_CONFIG['posts_per_page'])
  end

  def privacy

  end

  def books
    @subscription = Subscription.new
    @posts = NewsItem.books.order("posted_date DESC")
    # 10/14/2020 - Nicole no longer wants pagination on the books page.
    # @posts = NewsItem.books.order("posted_date DESC").paginate(page: params[:page], per_page: APP_CONFIG['posts_per_page'])
  end

  def contact
    @subscription = Subscription.new
  end

  def about
    @subscription = Subscription.new
  end

  def backdoor
  end

  def whitelist
  end

  def signup
    @subscription = Subscription.new
    @skip_nav = true
  end

  def subscribed
  end

  def email
    if verify_recaptcha
      data = params[:body]
      subject = params[:subject]
      @from_email = params[:email]
      ApplicationMailer.send_nicole_email(data, @from_email, subject).deliver
      penname = (ENV['PENNAME'] == 'nikki') ? 'Nikki' : 'Nicole'
      redirect_to root_path, notice: "We sent your email to #{penname}."
    else
      redirect_to root_path, notice: 'Please complete the captcha to subscribe.'
    end
  end
end

app/views/homes/_banner.html.erb
<% penname = (ENV['PENNAME'] == 'nikki') ? 'Nikki' : 'Nicole' %>
<!-- start banner Area -->
<div class="banner relative" id="home">
  <div >
    <div class="row align-items-center justify-content-center">
      <div class="banner-content py-4 col-md-12">
        <h1 class="<%= "banner-#{penname.downcase}" %>">
          <% if penname == 'Nikki' %>
          Nikki Hall Books
          <% else %>
          Nicole Hall Books
          <% end %>
        </h1>
        <h4><div class="tag-line-<%= penname.downcase %>" style="color: white;">
          <% if ENV['PENNAME'] == 'nikki' %>
          Sports <span class="nikki-dot"></span> Spice <span class="nikki-dot"></span> Sass
          <% else %>
          Magic. Sass. Love.
          <% end %>
        </div></h4>
      </div>
    </div>
  </div>
</div>
<!-- End banner Area -->

app/views/homes/_posts.html.erb
<div class="profile-container py-4">
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <% records.each do |post| %>
          <div class="news-post">

            <% unless hide_date %>
            <div class="d-flex justify-content-center">
              <p class="text-center">
                <a id="<%= post.title.parameterize(separator: '_') %>">
                  <%=post.posted_date.strftime('%B %d, %Y') %>
                </a>
              </p>
            </div>
            <% end %>

            <div class="d-flex justify-content-center">
               <p class="text-center">
                 <h1 class="news-title">
                  <%= post.title %>
                 </h1>
               </p>
            </div>
            <div class="d-flex justify-content-center">
              <% if post.picture.attached? %>
                <p class="">
                  <% if post.piclink.present? %>
                    <%= link_to post.piclink do %>
                      <image src="<%= url_for(post.picture) %>"></image>
                    <% end %>
                  <% else %>
                    <image src="<%= url_for(post.picture) %>"></image>
                  <% end %>
                </p>
              <% end %>
            </div>
            <p class="news-body fr-view"><%= raw post.body %></p>
          </div>
          <hr>
        <% end %>
      </div>
      <div class="col-md-3">
        <%= render 'layouts/sidebar' %>
      </div>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<%= page_heading "About" %>
<%= render 'banner' %>

<div class="profile-container py-4">
  <div class="container">
    <div class="row">
      <div class="col-md-9 profile-body ">
        <%= image_tag("NicoleHallBooks.jpg", style: 'float:left;height:250px;margin:10px;') %>
        <% penname = (ENV['PENNAME'] == 'nikki') ? 'Nikki' : 'Nicole' %>
        <% if ENV['PENNAME'] == 'nikki' %>

        <p>Nikki Hall is a smart-ass with a Ph.D. and a potty mouth. She writes stories that have spice and sass because she doesn't know any other way. Coffee makes her happy, messes make her stabby, and she’d sell one of her children for a second season of Firefly. She also writes paranormal romance under the name Nicole Hall.</p>

        <p>Let Nikki know what you thought about her books because she loves hearing from readers. Email her at nikkihallbooks@gmail.com, find her on TikTok at @nikkihallbooks, or follow her on Facebook at <%= link_to 'nikkihallbooks', 'https://www.facebook.com/nikkihallbooks' %></p>

        <p>Want to find out when the newest Nikki Hall book hits the shelves? Sign up for her newsletter to receive a free ebook plus new release info, giveaways, exclusive content, and previews of new books especially for fans.</p>

        <% else %>

        <p><%= penname %> Hall is a smart-ass with a Ph.D. and a potty mouth. She writes stories that have magic, sass, and romance because she believes that everyone deserves a little happiness. Coffee makes her happy, messes make her stabby, and she’d sell one of her children for a second season of Firefly. Her paranormal romance books are available on Amazon now.</p>

        <p>Let <%= penname %> know what you thought about her sassy, magical world because she really does love hearing from readers. Email her at nicolehallbooks@gmail.com or join her reader group <%= link_to 'Muse Interrupted Romance', 'https://www.facebook.com/groups/museinterrupted' %> on Facebook!</p>
        
        <p>Want to find out when the newest <%= penname %> Hall book hits the shelves? Sign up for her weekly newsletter. You’ll get a free ebook, plus new release info, giveaways, exclusive content, and previews of the new books especially for fans.</p>
        
        <% end %>
      </div>

      <div class="col-md-3 px-2">
        <%= render 'layouts/sidebar' %>
      </div>
    </div>
  </div>
</div>

app/views/homes/backdoor.html.erb
<div class="container justify-content-center p-4">
  <%= form_tag(validate_sessions_path, :method => "post") do %>
    <div class="row">
    	<%= text_field_tag :name %>
    </div>
    <div class="row">
    	<%= password_field_tag :secret %>
    </div>

    <div>
    	<%= submit_tag "Login", :class => 'btn btn-large btn-primary' %>
    </div>
  <% end %>
</div>

app/views/homes/books.html.erb
<%= page_heading "Books" %>
<%= render 'banner' %>

<!-- Start Books Area -->
<%= render partial: 'posts', locals: { records: @posts, hide_date: true } %>
<!-- End Books Area -->

app/views/homes/contact.html.erb
<%= page_heading "Contact" %>
<%= render 'banner' %>
<% penname = (ENV['PENNAME'] == 'nikki') ? 'Nikki' : 'Nicole' %>

<div class="profile-container py-4">
  <div class="container">
    <div class="row">
      <div class="col-md-9 profile-body ">
        <h1>Send <%= penname %> an Email</h1>

        <%= form_tag email_homes_path do%>

          <div class="row py-2">
            <div class="col-8">
              <%= label_tag :email, "Your Email Address", class: "font-weight-bold" %>
              <div class="input-group input-group-lg">
                <%= text_field_tag :email, '', placeholder: " Your Email Address ", class: 'form-control input-lg' %>
              </div>
            </div>
          </div>

          <div class="row py-2">
            <div class="col-8">
              <%= label_tag :subject, "Subject", class: "font-weight-bold" %>
              <div class="input-group input-group-lg">
                <%= text_field_tag :subject, '', placeholder: " Subject of your email ", class: 'form-control input-lg' %>
              </div>
            </div>
          </div>

          <div class="row py-2">
            <div class="col-8">
              <%= label_tag :body, "Email Message", class: "font-weight-bold" %>
              <div class="input-group input-group-lg">
                <%= text_area_tag :body, '', class: 'form-control input-lg', rows: "10" %>
              </div>
            </div>
          </div>
          <%= recaptcha_tags %>

          <%= submit_tag "Send", class: 'btn btn-primary py-2' %>

        <%end%>

        <p>You can find <%= penname %> at any of the following:</p>

        <p><a href="https://www.facebook.com/<%= penname.downcase %>hallbooks">Facebook</a></p>
        <p><a href="https://www.tiktok.com/@<%= penname.downcase %>hallbooks">TikTok</a></p>
        <p><a href="https://www.amazon.com/Nicole-Hall/e/B085VLG75K">Amazon</a></p>
        <p><a href="https://www.bookbub.com/authors/nicole-hall">Bookbub</a></p>
      </div>

      <div class="col-md-3 px-2">
        <%= render 'layouts/sidebar' %>
      </div>
  </div>
</div>

app/views/homes/old_signup.html.erb
<%= page_heading "Signup" %>
<%= render 'banner' %>

<div class="profile-container py-4">
  <div class="container">
    <div class="row">
      <div>
        <div class="signup-image-wrapper">
          <%= image_tag("Nicole_Hall_Many_Books.jpg", class: 'signup-image') %>
          <br>
        </div>

        <div id="signup_box" class="outer-grey-box">
          <div class="row-form inside-text">
            <div>
              <h4 class="signup-h4">How about a free book?</h4>
              <p class="signup-p">Sign up for my newsletter to receive a free ebook directly to your email. You'll also be the first to know about new releases, sales, giveaways, and more!</p>
              <br>
            </div>

            <%= form_for(@subscription) do |f| %>
            
              <div class="signup-form-content">
                <%= f.text_field :email, placeholder: " Your Email Address ", class: 'form-control input-lg' %>
              </div>

              <div class="signup-form-perms" style="">
                <div class="default signup-form-perms">
                  <h4>Marketing Permissions</h4>
                  <p>The information you provide will only be used to send you your free book and add you to Nicole's newsletter.&nbsp;Your privacy is important to us. Click below to be added to the email list!</p>
                  <div>
                    <label>
                      <input type="checkbox" name="agree" value="Email" class="email-checkbox" onchange="document.getElementById('sendsub').disabled = !this.checked;">
                      <div class="email-label">Email</div>
                    </label>
                    <div class="description">We will send you occasional emails about promotions, new books, and important updates to keep you in the loop.</div>
                  </div>
                </div>
                <div class="mailer-info">
                  <p>We use MailerLite as our marketing automation platform. By clicking below to submit this form, you acknowledge that the information you provide will be transferred to MailerLite for processing in accordance with their <a href="https://www.mailerlite.com/privacy-policy" target="_blank">Privacy Policy</a> and <a href="https://www.mailerlite.com/terms-of-service" target="_blank">Terms of Service</a>.</p>
                </div>
              </div>
              
              <%= recaptcha_tags %>

              <div>
                <button type="submit" class="primary subscribe-button" disabled id="sendsub">Subscribe</button>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/homes/privacy.html.erb
<%= page_heading "Privacy" %>
<%= render 'banner' %>

<div class="py-4">
  <div class="container">
    <h3>Privacy Policy</h3>

    <p>February 24, 2020</p>

    <p>This Privacy Policy is designed to inform you about what personally identifiable information
    (PII) this website collects and what may be done with that PII.</p>

    <p>You are not required to submit any PII to use this website. However, the server for this website
    may collect data about your visit, your computer’s IP address, browser type, operating system,
    geographic location, referral source, pages visited, and other “analytics” data. I may review that
    data from time to time to understand how the website is used and to improve the website for
    users. I do not currently provide that data to any third parties, but may in the future release it to
    publishers or agents interested in my work.</p>

    <p>I do not track users after they visit my site.
    At your election, you may provide your email address to receive my newsletter and other emails.
    If at any time you would like me to remove your PII from my database, please email me directly
    at nicolehallbooks@gmail.com. You may unsubscribe from my blog and mailing list by clicking
    on the unsubscribe link on any newsletter.</p>

    <p>Please do not disclose to me the PII of any other person without that person’s consent.
    This site is directed to adults and not directed to children under the age of 13. I ask that minors
    not submit any PII. This site complies with the Children’s Online Privacy Protection Act and
    does not permit registration by, and will not knowingly collect personally identifiable
    information from, anyone under 13 years of age.</p>

    <p>I will take reasonable technical precautions to prevent the loss, misused or alteration of your PII.</p>

    <p>I will not provide your email address or any other PII to any other person, other than (i) to
    Mailerlite or other provider which assists me in sending newsletters and emails, or (ii) if required
    to be disclosed by law or in connection with any actual or threatened legal proceeding.
    My website includes hyperlinks to other websites. I have no control over and am not responsible
    for the privacy policies and practices of other websites and blogs.</p>

    <p>You may copy and quote from my website and blog without limitation, so long as you provide
    attribution to me and a link back to my site.</p>

    <p>I may update this Privacy Policy from time to time by posting an undated version on my website.</p>

  </div>
</div>

app/views/homes/show.html.erb
<%= page_heading "Home" %>
<%= render 'banner' %>

<!-- Start News Post Area -->
<%= render partial: 'posts', locals: { records: @posts, hide_date: false } %>
<!-- End News Post Area -->

app/views/homes/signup.html.erb
<% penname = (ENV['PENNAME'] == 'nikki') ? 'Nikki' : 'Nicole' %>
<%= page_heading "Signup" %>

<div class="full-2 py-4">
  <div class="banner2">
    <div>
      <div class="row">
        <div class="banner-content2 py-0 col-md-12">
          <h1 class="">
            <%= penname %> Hall Books
          </h1>
        </div>
      </div>
    </div>
  </div>
  <div class="container vertical-center">

    <div class="row align-items-center justify-content-center" style="width: 100%">
      <div class="col-4">
        <% if ENV['PENNAME'] == 'nikki' %>
          <%= image_tag("nikki-signup-book.png", class: 'signup-image', style: 'min-height: 400px;') %>
        <% else %>
          <%= image_tag("signupimage.png", class: 'signup-image') %>
        <% end %>
      </div>

      <div id="signup_box" class="outer-grey-box col-8 align-items-center justify-content-center"  style="text-align: center;">
        <div class="row-form inside-text">
          <div class="align-items-center justify-content-center"  style="text-align: center;">
            <% if ENV['PENNAME'] == 'nikki' %>
              <h4 class="signup-h4">Sports. Spice. Sass.</h4>
            <% else %>
              <h4 class="signup-h4">Magic. Sass. Romance.</h4>
            <% end %>
            <p class="signup-p">To get your free ebook, you just need to tell me where to send it. Enter your email address to get your story delivered to your inbox. You'll also be added to my weekly newsletter, and you'll be the first to know next time I have some cool stuff to give away (you can unsubscribe at any time).</p>
            <br>
          </div>

          <%= form_for(@subscription) do |f| %>
            <div class="signup-form-content row align-items-center justify-content-center">
              <%= f.text_field :email, placeholder: " Your Email Address ", class: 'form-control input-lg col-6' %>
              <button type="submit" class="subscribe-button col-4" id="sendsub">Send My Free Book</button>
            </div>
            <br>
            <div>
              (We value your privacy and would never spam you)
            </div>
          <% end %>
        </div>
      </div> <!-- text block and subscribe area -->
    </div> <!-- image/subscribe row -->
  </div>
</div>

app/views/homes/subscribed.html.erb
<%= page_heading "Contact" %>
<%= render 'banner' %>

<div class="full-2 py-4">
  <div class="container vertical-center">
    <div class="row">
      <div class="col-4"></div>
      <div class="col-md-7 profile-body ">
      	<br>
      	<br>
        <h1>Thank you</h1>
        <br>
        <p>Almost finished, I need to confirm your email address.</p>
        <p>Please click the link in the email I just sent you and we're done.</p>
        <br>

        <%= button_to 'Back to Home', root_path, class: "home-button", method: :get %>
      </div>
    </div>
  </div>
</div>

app/views/homes/thank_you.html.erb
<%= page_heading "Thank You" %>
<%= render 'banner' %>

<div class="py-4">
  <div class="container">
    <br><br>
    <h1>Thank You!</h1>
  </div>
</div>