config/routes.rb
Rails.application.routes.draw do
  resources :groups
  root to: "homes#show"

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy] do
    collection do
      post :ready
      post :validate
    end
  end

  resource :homes, only: [:show], :path => "/" do
    collection do
      get :contact
      get :books
      get :about
      get :backdoor
      post :email
      get :privacy
      get :whitelist
      get :signup
      get :subscribed
      get :thank_you
    end
  end

  resources :news_items
  resources :subscriptions, only: [:create]
end

app/views/layouts/_facebook_pixel.html.erb
<!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s)
{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};
if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)}(window,document,'script',
'https://connect.facebook.net/en_US/fbevents.js');
 fbq('init', '2809295432660528'); 
fbq('track', 'PageView');
</script>
<noscript>
 <img height="1" width="1" 
src="https://www.facebook.com/tr?id=2809295432660528&ev=PageView
&noscript=1"/>
</noscript>
<!-- End Facebook Pixel Code -->

app/views/layouts/_nav2.html.erb
<% penname = (ENV['PENNAME'] == 'nikki') ? 'Nikki' : 'Nicole' %>
<!-- Start Navigation Area -->
<nav class="navbar navbar-default navbar-expand-md fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <!-- hamburger button to toggle menu -->
      <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="fas fa-bars"></span>
      </button>
    </div>

    <!-- Collect the nav links for toggling -->
    <div class="collapse navbar-collapse col-md-9" id="navbar-collapse-1">
      <ul class="nav navbar-nav mx-auto">
        <li><%= link_to(root_path, class: "nav-item nav-link active") do %>
            <span class="lnr lnr-home" style='margin: 5px;'></span>HOME
          <% end %>
        </li>

        <li class="nav-item dropdown">
          <%= link_to(books_homes_path, class: "nav-link  dropdown-toggle", data: {toggle:"dropdown"}) do %>
            <span class="lnr lnr-book" style='margin: 5px;'></span>BOOKS
          <% end %>

          <ul class="dropdown-menu">
            <% Group.order(:ordering).each do |group| %>
              <li>
                <%= link_to(group.name, group, class: "dropdown-item") %>
              </li>
            <% end %>
          </ul>
        </li>

        <li><%= link_to(about_homes_path, class: "nav-item nav-link") do %>
            <span class="lnr lnr-list" style='margin: 5px;'></span>ABOUT
          <% end %></li>
        <li><%= link_to(contact_homes_path, class: "nav-item nav-link") do %>
            <span class="lnr lnr-inbox" style='margin: 5px;'></span>CONTACT
          <% end %></li>
      </ul>
    </div>

    <!-- These links are separate from the toggled links -->
    <div id="social-links" class="col-md-3 px-0">
      <%= link_to('https://www.bookbub.com/authors/nicole-hall', class: "nav-item nav-link", title: 'BookBub') do %><%= image_tag 'bookbub.png', width: 25, height: 25, alt: 'BookBub'%><% end %>
      <%= link_to("https://www.tiktok.com/@#{penname.downcase}hallbooks", class: "nav-item nav-link", title: 'TikTok') do image_tag('fa5/brands/tiktok.svg', height: '25px', style: "color: black;") end %>
      <%= link_to("https://www.facebook.com/#{penname.downcase}hallbooks", class: "nav-item nav-link", title: 'Facebook') do image_tag('fa5/brands/facebook.svg', height: '25px', style: "color: black;") end %>    
      <%= link_to('https://www.amazon.com/Nicole-Hall/e/B085VLG75K', class: "nav-item nav-link", title: 'Amazon')  do image_tag('fa5/brands/amazon.svg', height: '25px', style: "color: black;") end %>


      <% if current_user.present? %>
        <%= link_to "Sign out", signout_path, class: "nav-item nav-link" %>
      <% end %>
    </div>
  </div>
</nav>
<!-- End Navigation Area -->

app/views/layouts/_pinterest_claim.html.erb
<meta name="p:domain_verify" content="fef73673bf829e92e4707b589167a97c"/>

app/views/layouts/_sidebar.html.erb
<% penname = (ENV['PENNAME'] == 'nikki') ? 'Nikki' : 'Nicole' %>

<div class="py-5 pl-4" id="subscribe-floater">
  <h3>Want a FREE book?</h3>
  <p>Sign up for <%= penname %> Hall's newsletter. You’ll get a free ebook just for joining, plus new release info, giveaways, exclusive content, and previews of new books especially for fans.</p>

  <div id="subscribe-contents">
    <%= form_for(@subscription) do |f| %>
      <div class="row">
        <div class="col-12">
          <%= f.label :email, "Email", class: "font-weight-bold" %>
          <div class="input-group input-group-lg">
            <%= f.text_field :email, placeholder: " Your Email Address ",
              class: 'form-control input-lg' %>
          </div>
        </div>
      </div>
      <%= recaptcha_tags %>
      <%= f.submit "Subscribe", class: 'btn my-2', style: 'background: #AF32B2; color: white;' %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/facebook_pixel' %>
    <%= render 'layouts/pinterest_claim' %>
  </head>

  <body class="">
    <%= render 'layouts/nav2' unless defined?(@skip_nav) %>
    <%= render 'layouts/nav3' if defined?(@skip_nav) %>
    <section class="top-spacer relative" id="top"></section>

    <%= yield %>
  </body>

  <footer>
    <div class="d-flex justify-content-center p-3">
      <%= link_to(privacy_homes_path, class: "nav-item nav-link active") do %>
        <span class="lnr lnr-pushpin" style='margin: 5px;'></span>Privacy Policy
      <% end %>
    </div>
  </footer>
</html>